/* This file is auto-generated from "context.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef CONTEXT_L_H
#define CONTEXT_L_H

/** @page P_EBC_CONTEXT_LIB EBC_Context (lib)
This page describes the properties of EBC_CONTEXT
*/
#ifdef __cplusplus
extern "C" {
#endif

typedef struct EBC_CONTEXT EBC_CONTEXT;

#ifdef __cplusplus
} /* __cplusplus */
#endif

#include <gwenhywfar/misc.h>
#include <gwenhywfar/list2.h>
#include <gwenhywfar/misc.h>
#include <gwenhywfar/db.h>
#include <aqebics/aqebics.h>
#include <aqbanking/job_be.h>

#ifdef __cplusplus
extern "C" {
#endif


GWEN_LIST_FUNCTION_DEFS(EBC_CONTEXT, EBC_Context)
EBC_CONTEXT_LIST *EBC_Context_List_dup(const EBC_CONTEXT_LIST *stl);

GWEN_LIST2_FUNCTION_DEFS(EBC_CONTEXT, EBC_Context)

void EBC_Context_List2_freeAll(EBC_CONTEXT_LIST2 *stl);

EBC_CONTEXT *EBC_Context_new();
EBC_CONTEXT *EBC_Context_fromDb(GWEN_DB_NODE *db);
EBC_CONTEXT *EBC_Context_dup(const EBC_CONTEXT*st);
void EBC_Context_free(EBC_CONTEXT *st);
void EBC_Context_Attach(EBC_CONTEXT *st);
int EBC_Context_ReadDb(EBC_CONTEXT *st, GWEN_DB_NODE *db);
int EBC_Context_toDb(const EBC_CONTEXT*st, GWEN_DB_NODE *db);
int EBC_Context_IsModified(const EBC_CONTEXT *st);
void EBC_Context_SetModified(EBC_CONTEXT *st, int i);

/**
* Returns the property @ref EBC_CONTEXT_Jobs
*/
AB_JOB_LIST2 *EBC_Context_GetJobs(const EBC_CONTEXT *el);
/**
* Set the property @ref EBC_CONTEXT_Jobs
*/
void EBC_Context_SetJobs(EBC_CONTEXT *el, AB_JOB_LIST2 *d);

/**
* Returns the property @ref EBC_CONTEXT_JobType
*/
AB_JOB_TYPE EBC_Context_GetJobType(const EBC_CONTEXT *el);
/**
* Set the property @ref EBC_CONTEXT_JobType
*/
void EBC_Context_SetJobType(EBC_CONTEXT *el, AB_JOB_TYPE d);


#ifdef __cplusplus
} /* __cplusplus */
#endif


#endif /* CONTEXT_L_H */
