/* This file is auto-generated from "context.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef CONTEXT_P_H
#define CONTEXT_P_H

#include "context_l.h"


struct EBC_CONTEXT {
  GWEN_LIST_ELEMENT(EBC_CONTEXT)
  int _usage;
  int _modified;

  AB_JOB_LIST2 *jobs;
  AB_JOB_TYPE jobType;
};





#endif /* CONTEXT_P_H */
