/* This file is auto-generated from "tanmethod.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef TANMETHOD_L_H
#define TANMETHOD_L_H

/** @page P_AH_TAN_METHOD_LIB AH_TanMethod (lib)
This page describes the properties of AH_TAN_METHOD
This group represents a TAN method within AqHBCI.
*/
#include "tanmethod.h"

#ifdef __cplusplus
extern "C" {
#endif





























#ifdef __cplusplus
} /* __cplusplus */
#endif


#endif /* TANMETHOD_L_H */
