/* This file is auto-generated from "mediumctx.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef MEDIUMCTX_L_H
#define MEDIUMCTX_L_H

/** @page P_AH_MEDIUM_CTX_LIB AH_MediumCtx (lib)
This page describes the properties of AH_MEDIUM_CTX
*/
#include <gwenhywfar/misc.h>
#include <gwenhywfar/list2.h>
#include "mediumctx.h"
#include <gwenhywfar/misc.h>

#ifdef __cplusplus
extern "C" {
#endif

GWEN_LIST_FUNCTION_DEFS(AH_MEDIUM_CTX, AH_MediumCtx)
AH_MEDIUM_CTX_LIST *AH_MediumCtx_List_dup(const AH_MEDIUM_CTX_LIST *stl);
GWEN_LIST2_FUNCTION_DEFS(AH_MEDIUM_CTX, AH_MediumCtx)

void AH_MediumCtx_List2_freeAll(AH_MEDIUM_CTX_LIST2 *stl);
AH_MEDIUM_CTX_LIST2 *AH_MediumCtx_List2_dup(const AH_MEDIUM_CTX_LIST2 *stl);









#ifdef __cplusplus
} /* __cplusplus */
#endif


#endif /* MEDIUMCTX_L_H */
