/* This file is auto-generated from "mediumctx.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef MEDIUMCTX_P_H
#define MEDIUMCTX_P_H

#include "mediumctx_l.h"


struct AH_MEDIUM_CTX {
  GWEN_LIST_ELEMENT(AH_MEDIUM_CTX)
  int _usage;
  int _modified;

  GWEN_CRYPTTOKEN_USER *user;
  GWEN_CRYPTTOKEN_CONTEXT *tokenContext;
  GWEN_KEYSPEC *localSignKeySpec;
  GWEN_KEYSPEC *localCryptKeySpec;
  GWEN_KEYSPEC *remoteSignKeySpec;
  GWEN_KEYSPEC *remoteCryptKeySpec;
};









#endif /* MEDIUMCTX_P_H */
