/* This file is auto-generated from "mediumctx.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifdef HAVE_CONFIG_H
# include "config.h"
#endif

#include "mediumctx_p.h"
#include <gwenhywfar/misc.h>
#include <gwenhywfar/db.h>
#include <gwenhywfar/debug.h>
#include <assert.h>
#include <stdlib.h>
#include <strings.h>


GWEN_LIST_FUNCTIONS(AH_MEDIUM_CTX, AH_MediumCtx)
GWEN_LIST2_FUNCTIONS(AH_MEDIUM_CTX, AH_MediumCtx)


AH_MEDIUM_CTX *AH_MediumCtx_new() {
  AH_MEDIUM_CTX *st;

  GWEN_NEW_OBJECT(AH_MEDIUM_CTX, st)
  st->_usage=1;
  GWEN_LIST_INIT(AH_MEDIUM_CTX, st)
  return st;
}


void AH_MediumCtx_free(AH_MEDIUM_CTX *st) {
  if (st) {
    assert(st->_usage);
    if (--(st->_usage)==0) {
  if (st->user)
    GWEN_CryptToken_User_free(st->user);
  if (st->tokenContext)
    GWEN_CryptToken_Context_free(st->tokenContext);
  if (st->localSignKeySpec)
    GWEN_KeySpec_free(st->localSignKeySpec);
  if (st->localCryptKeySpec)
    GWEN_KeySpec_free(st->localCryptKeySpec);
  if (st->remoteSignKeySpec)
    GWEN_KeySpec_free(st->remoteSignKeySpec);
  if (st->remoteCryptKeySpec)
    GWEN_KeySpec_free(st->remoteCryptKeySpec);
  GWEN_LIST_FINI(AH_MEDIUM_CTX, st)
  GWEN_FREE_OBJECT(st);
    }
  }

}


AH_MEDIUM_CTX *AH_MediumCtx_dup(const AH_MEDIUM_CTX *d) {
  AH_MEDIUM_CTX *st;

  assert(d);
  st=AH_MediumCtx_new();
  if (d->user)
    st->user=GWEN_CryptToken_User_dup(d->user);
  if (d->tokenContext)
    st->tokenContext=GWEN_CryptToken_Context_dup(d->tokenContext);
  if (d->localSignKeySpec)
    st->localSignKeySpec=GWEN_KeySpec_dup(d->localSignKeySpec);
  if (d->localCryptKeySpec)
    st->localCryptKeySpec=GWEN_KeySpec_dup(d->localCryptKeySpec);
  if (d->remoteSignKeySpec)
    st->remoteSignKeySpec=GWEN_KeySpec_dup(d->remoteSignKeySpec);
  if (d->remoteCryptKeySpec)
    st->remoteCryptKeySpec=GWEN_KeySpec_dup(d->remoteCryptKeySpec);
  return st;
}


int AH_MediumCtx_toDb(const AH_MEDIUM_CTX *st, GWEN_DB_NODE *db) {
  assert(st);
  assert(db);
  if (st->user)
    if (GWEN_CryptToken_User_toDb(st->user, GWEN_DB_GetGroup(db, GWEN_DB_FLAGS_DEFAULT, "user")))
      return -1;
  if (st->tokenContext)
    if (GWEN_CryptToken_Context_toDb(st->tokenContext, GWEN_DB_GetGroup(db, GWEN_DB_FLAGS_DEFAULT, "tokenContext")))
      return -1;
  if (st->localSignKeySpec)
    if (GWEN_KeySpec_toDb(st->localSignKeySpec, GWEN_DB_GetGroup(db, GWEN_DB_FLAGS_DEFAULT, "localSignKeySpec")))
      return -1;
  if (st->localCryptKeySpec)
    if (GWEN_KeySpec_toDb(st->localCryptKeySpec, GWEN_DB_GetGroup(db, GWEN_DB_FLAGS_DEFAULT, "localCryptKeySpec")))
      return -1;
  if (st->remoteSignKeySpec)
    if (GWEN_KeySpec_toDb(st->remoteSignKeySpec, GWEN_DB_GetGroup(db, GWEN_DB_FLAGS_DEFAULT, "remoteSignKeySpec")))
      return -1;
  if (st->remoteCryptKeySpec)
    if (GWEN_KeySpec_toDb(st->remoteCryptKeySpec, GWEN_DB_GetGroup(db, GWEN_DB_FLAGS_DEFAULT, "remoteCryptKeySpec")))
      return -1;
  return 0;
}


AH_MEDIUM_CTX *AH_MediumCtx_fromDb(GWEN_DB_NODE *db) {
AH_MEDIUM_CTX *st;

  assert(db);
  st=AH_MediumCtx_new();
  if (1) {
    GWEN_DB_NODE *dbT;

    dbT=GWEN_DB_GetGroup(db, GWEN_PATH_FLAGS_NAMEMUSTEXIST, "user");
    if (dbT)  AH_MediumCtx_SetUser(st, GWEN_CryptToken_User_fromDb(dbT));
  }
  if (1) {
    GWEN_DB_NODE *dbT;

    dbT=GWEN_DB_GetGroup(db, GWEN_PATH_FLAGS_NAMEMUSTEXIST, "tokenContext");
    if (dbT)  AH_MediumCtx_SetTokenContext(st, GWEN_CryptToken_Context_fromDb(dbT));
  }
  if (1) {
    GWEN_DB_NODE *dbT;

    dbT=GWEN_DB_GetGroup(db, GWEN_PATH_FLAGS_NAMEMUSTEXIST, "localSignKeySpec");
    if (dbT)  AH_MediumCtx_SetLocalSignKeySpec(st, GWEN_KeySpec_fromDb(dbT));
  }
  if (1) {
    GWEN_DB_NODE *dbT;

    dbT=GWEN_DB_GetGroup(db, GWEN_PATH_FLAGS_NAMEMUSTEXIST, "localCryptKeySpec");
    if (dbT)  AH_MediumCtx_SetLocalCryptKeySpec(st, GWEN_KeySpec_fromDb(dbT));
  }
  if (1) {
    GWEN_DB_NODE *dbT;

    dbT=GWEN_DB_GetGroup(db, GWEN_PATH_FLAGS_NAMEMUSTEXIST, "remoteSignKeySpec");
    if (dbT)  AH_MediumCtx_SetRemoteSignKeySpec(st, GWEN_KeySpec_fromDb(dbT));
  }
  if (1) {
    GWEN_DB_NODE *dbT;

    dbT=GWEN_DB_GetGroup(db, GWEN_PATH_FLAGS_NAMEMUSTEXIST, "remoteCryptKeySpec");
    if (dbT)  AH_MediumCtx_SetRemoteCryptKeySpec(st, GWEN_KeySpec_fromDb(dbT));
  }
  st->_modified=0;
  return st;
}


GWEN_CRYPTTOKEN_USER *AH_MediumCtx_GetUser(const AH_MEDIUM_CTX *st) {
  assert(st);
  return st->user;
}


void AH_MediumCtx_SetUser(AH_MEDIUM_CTX *st, GWEN_CRYPTTOKEN_USER *d) {
  assert(st);
  if (st->user)
    GWEN_CryptToken_User_free(st->user);
  if (d)
    st->user=GWEN_CryptToken_User_dup(d);
  else
    st->user=0;
  st->_modified=1;
}


GWEN_CRYPTTOKEN_CONTEXT *AH_MediumCtx_GetTokenContext(const AH_MEDIUM_CTX *st) {
  assert(st);
  return st->tokenContext;
}


void AH_MediumCtx_SetTokenContext(AH_MEDIUM_CTX *st, GWEN_CRYPTTOKEN_CONTEXT *d) {
  assert(st);
  if (st->tokenContext)
    GWEN_CryptToken_Context_free(st->tokenContext);
  if (d)
    st->tokenContext=GWEN_CryptToken_Context_dup(d);
  else
    st->tokenContext=0;
  st->_modified=1;
}


const GWEN_KEYSPEC *AH_MediumCtx_GetLocalSignKeySpec(const AH_MEDIUM_CTX *st) {
  assert(st);
  return st->localSignKeySpec;
}


void AH_MediumCtx_SetLocalSignKeySpec(AH_MEDIUM_CTX *st, const GWEN_KEYSPEC *d) {
  assert(st);
  if (st->localSignKeySpec)
    GWEN_KeySpec_free(st->localSignKeySpec);
  if (d)
    st->localSignKeySpec=GWEN_KeySpec_dup(d);
  else
    st->localSignKeySpec=0;
  st->_modified=1;
}


const GWEN_KEYSPEC *AH_MediumCtx_GetLocalCryptKeySpec(const AH_MEDIUM_CTX *st) {
  assert(st);
  return st->localCryptKeySpec;
}


void AH_MediumCtx_SetLocalCryptKeySpec(AH_MEDIUM_CTX *st, const GWEN_KEYSPEC *d) {
  assert(st);
  if (st->localCryptKeySpec)
    GWEN_KeySpec_free(st->localCryptKeySpec);
  if (d)
    st->localCryptKeySpec=GWEN_KeySpec_dup(d);
  else
    st->localCryptKeySpec=0;
  st->_modified=1;
}


const GWEN_KEYSPEC *AH_MediumCtx_GetRemoteSignKeySpec(const AH_MEDIUM_CTX *st) {
  assert(st);
  return st->remoteSignKeySpec;
}


void AH_MediumCtx_SetRemoteSignKeySpec(AH_MEDIUM_CTX *st, const GWEN_KEYSPEC *d) {
  assert(st);
  if (st->remoteSignKeySpec)
    GWEN_KeySpec_free(st->remoteSignKeySpec);
  if (d)
    st->remoteSignKeySpec=GWEN_KeySpec_dup(d);
  else
    st->remoteSignKeySpec=0;
  st->_modified=1;
}


const GWEN_KEYSPEC *AH_MediumCtx_GetRemoteCryptKeySpec(const AH_MEDIUM_CTX *st) {
  assert(st);
  return st->remoteCryptKeySpec;
}


void AH_MediumCtx_SetRemoteCryptKeySpec(AH_MEDIUM_CTX *st, const GWEN_KEYSPEC *d) {
  assert(st);
  if (st->remoteCryptKeySpec)
    GWEN_KeySpec_free(st->remoteCryptKeySpec);
  if (d)
    st->remoteCryptKeySpec=GWEN_KeySpec_dup(d);
  else
    st->remoteCryptKeySpec=0;
  st->_modified=1;
}


int AH_MediumCtx_IsModified(const AH_MEDIUM_CTX *st) {
  assert(st);
  return st->_modified;
}


void AH_MediumCtx_SetModified(AH_MEDIUM_CTX *st, int i) {
  assert(st);
  st->_modified=i;
}


void AH_MediumCtx_Attach(AH_MEDIUM_CTX *st) {
  assert(st);
  st->_usage++;
}
AH_MEDIUM_CTX *AH_MediumCtx_List2__freeAll_cb(AH_MEDIUM_CTX *st, void *user_data) {
  AH_MediumCtx_free(st);
return 0;
}


void AH_MediumCtx_List2_freeAll(AH_MEDIUM_CTX_LIST2 *stl) {
  if (stl) {
    AH_MediumCtx_List2_ForEach(stl, AH_MediumCtx_List2__freeAll_cb, 0);
    AH_MediumCtx_List2_free(stl); 
  }
}




AH_MEDIUM_CTX_LIST *AH_MediumCtx_List_dup(const AH_MEDIUM_CTX_LIST *stl) {
  if (stl) {
    AH_MEDIUM_CTX_LIST *nl;
    AH_MEDIUM_CTX *e;

    nl=AH_MediumCtx_List_new();
    e=AH_MediumCtx_List_First(stl);
    while(e) {
      AH_MEDIUM_CTX *ne;

      ne=AH_MediumCtx_dup(e);
      assert(ne);
      AH_MediumCtx_List_Add(ne, nl);
      e=AH_MediumCtx_List_Next(e);
    } /* while (e) */
    return nl;
  }
  else
    return 0;
}



