/**********************************************************
 * This file has been automatically created by "typemaker2"
 * from the file "oh_institute_data.xml".
 * Please do not edit this file, all changes will be lost.
 * Better edit the mentioned source file instead.
 **********************************************************/

#ifndef OH_INSTITUTE_DATA_OH_INSTITUTE_DATA_H
#define OH_INSTITUTE_DATA_OH_INSTITUTE_DATA_H


#ifdef __cplusplus
extern "C" {
#endif

/** @page P_OH_INSTITUTE_DATA Structure OH_INSTITUTE_DATA
<p>This page describes the properties of OH_INSTITUTE_DATA.</p>



<h1>OH_INSTITUTE_DATA</h1>



@anchor OH_INSTITUTE_DATA_id
<h2>id</h2>

<p>Set this property with @ref OH_InstituteData_SetId(), get it with @ref OH_InstituteData_GetId().</p>


@anchor OH_INSTITUTE_DATA_flags
<h2>flags</h2>

<p>Set this property with @ref OH_InstituteData_SetFlags(), get it with @ref OH_InstituteData_GetFlags().</p>


@anchor OH_INSTITUTE_DATA_name
<h2>name</h2>

<p>Set this property with @ref OH_InstituteData_SetName(), get it with @ref OH_InstituteData_GetName().</p>


@anchor OH_INSTITUTE_DATA_fid
<h2>fid</h2>

<p>Set this property with @ref OH_InstituteData_SetFid(), get it with @ref OH_InstituteData_GetFid().</p>


@anchor OH_INSTITUTE_DATA_org
<h2>org</h2>

<p>Set this property with @ref OH_InstituteData_SetOrg(), get it with @ref OH_InstituteData_GetOrg().</p>


@anchor OH_INSTITUTE_DATA_brokerId
<h2>brokerId</h2>

<p>Set this property with @ref OH_InstituteData_SetBrokerId(), get it with @ref OH_InstituteData_GetBrokerId().</p>


@anchor OH_INSTITUTE_DATA_url
<h2>url</h2>

<p>Set this property with @ref OH_InstituteData_SetUrl(), get it with @ref OH_InstituteData_GetUrl().</p>


@anchor OH_INSTITUTE_DATA_lastOfxValidationTime
<h2>lastOfxValidationTime</h2>

<p>Set this property with @ref OH_InstituteData_SetLastOfxValidationTime(), get it with @ref OH_InstituteData_GetLastOfxValidationTime().</p>


@anchor OH_INSTITUTE_DATA_lastSslValidationTime
<h2>lastSslValidationTime</h2>

<p>Set this property with @ref OH_InstituteData_SetLastSslValidationTime(), get it with @ref OH_InstituteData_GetLastSslValidationTime().</p>


@anchor OH_INSTITUTE_DATA_fileName
<h2>fileName</h2>

<p>Set this property with @ref OH_InstituteData_SetFileName(), get it with @ref OH_InstituteData_GetFileName().</p>

*/

/* define OH_INSTITUTE_DATA_FLAGS */
#define OH_INSTITUTE_DATA_FLAGS_OFXFAIL 0x00000001
#define OH_INSTITUTE_DATA_FLAGS_SSLFAIL 0x00000002


/* needed system headers */
#include <gwenhywfar/types.h>
#include <gwenhywfar/list1.h>
#include <gwenhywfar/list2.h>
#include <gwenhywfar/db.h>

/* pre-headers */
#include <aqofxconnect/aqofxconnect.h>
#include <gwenhywfar/gwentime.h>

typedef struct OH_INSTITUTE_DATA OH_INSTITUTE_DATA;
GWEN_LIST_FUNCTION_DEFS(OH_INSTITUTE_DATA, OH_InstituteData)
GWEN_LIST2_FUNCTION_DEFS(OH_INSTITUTE_DATA, OH_InstituteData)



/* post-headers */
#include <aqofxconnect/libofxhome/oh_institute_data_fns.h>


/** Constructor. */
OH_INSTITUTE_DATA *OH_InstituteData_new(void);

/** Destructor. */
void OH_InstituteData_free(OH_INSTITUTE_DATA *p_struct);

void OH_InstituteData_Attach(OH_INSTITUTE_DATA *p_struct);

OH_INSTITUTE_DATA *OH_InstituteData_dup(const OH_INSTITUTE_DATA *p_src);

OH_INSTITUTE_DATA *OH_InstituteData_copy(OH_INSTITUTE_DATA *p_struct, const OH_INSTITUTE_DATA *p_src);

/** Getter.
 * Use this function to get the member "id" (see @ref OH_INSTITUTE_DATA_id)
*/
int OH_InstituteData_GetId(const OH_INSTITUTE_DATA *p_struct);

/** Getter.
 * Use this function to get the member "flags" (see @ref OH_INSTITUTE_DATA_flags)
*/
uint32_t OH_InstituteData_GetFlags(const OH_INSTITUTE_DATA *p_struct);

/** Getter.
 * Use this function to get the member "name" (see @ref OH_INSTITUTE_DATA_name)
*/
const char *OH_InstituteData_GetName(const OH_INSTITUTE_DATA *p_struct);

/** Getter.
 * Use this function to get the member "fid" (see @ref OH_INSTITUTE_DATA_fid)
*/
const char *OH_InstituteData_GetFid(const OH_INSTITUTE_DATA *p_struct);

/** Getter.
 * Use this function to get the member "org" (see @ref OH_INSTITUTE_DATA_org)
*/
const char *OH_InstituteData_GetOrg(const OH_INSTITUTE_DATA *p_struct);

/** Getter.
 * Use this function to get the member "brokerId" (see @ref OH_INSTITUTE_DATA_brokerId)
*/
const char *OH_InstituteData_GetBrokerId(const OH_INSTITUTE_DATA *p_struct);

/** Getter.
 * Use this function to get the member "url" (see @ref OH_INSTITUTE_DATA_url)
*/
const char *OH_InstituteData_GetUrl(const OH_INSTITUTE_DATA *p_struct);

/** Getter.
 * Use this function to get the member "lastOfxValidationTime" (see @ref OH_INSTITUTE_DATA_lastOfxValidationTime)
*/
const GWEN_TIME *OH_InstituteData_GetLastOfxValidationTime(const OH_INSTITUTE_DATA *p_struct);

/** Getter.
 * Use this function to get the member "lastSslValidationTime" (see @ref OH_INSTITUTE_DATA_lastSslValidationTime)
*/
const GWEN_TIME *OH_InstituteData_GetLastSslValidationTime(const OH_INSTITUTE_DATA *p_struct);

/** Getter.
 * Use this function to get the member "fileName" (see @ref OH_INSTITUTE_DATA_fileName)
*/
const char *OH_InstituteData_GetFileName(const OH_INSTITUTE_DATA *p_struct);

/** Setter.
 * Use this function to set the member "id" (see @ref OH_INSTITUTE_DATA_id)
*/
void OH_InstituteData_SetId(OH_INSTITUTE_DATA *p_struct, int p_src);

/** Setter.
 * Use this function to set the member "flags" (see @ref OH_INSTITUTE_DATA_flags)
*/
void OH_InstituteData_SetFlags(OH_INSTITUTE_DATA *p_struct, uint32_t p_src);

/** Add flags.
 * Use this function to add flags to member "flags" (see @ref OH_INSTITUTE_DATA_flags)
*/
void OH_InstituteData_AddFlags(OH_INSTITUTE_DATA *p_struct, uint32_t p_src);
/** Add flags.
 * Use this function to add flags to member "flags" (see @ref OH_INSTITUTE_DATA_flags)
*/
void OH_InstituteData_SubFlags(OH_INSTITUTE_DATA *p_struct, uint32_t p_src);

/** Setter.
 * Use this function to set the member "name" (see @ref OH_INSTITUTE_DATA_name)
*/
void OH_InstituteData_SetName(OH_INSTITUTE_DATA *p_struct, const char *p_src);

/** Setter.
 * Use this function to set the member "fid" (see @ref OH_INSTITUTE_DATA_fid)
*/
void OH_InstituteData_SetFid(OH_INSTITUTE_DATA *p_struct, const char *p_src);

/** Setter.
 * Use this function to set the member "org" (see @ref OH_INSTITUTE_DATA_org)
*/
void OH_InstituteData_SetOrg(OH_INSTITUTE_DATA *p_struct, const char *p_src);

/** Setter.
 * Use this function to set the member "brokerId" (see @ref OH_INSTITUTE_DATA_brokerId)
*/
void OH_InstituteData_SetBrokerId(OH_INSTITUTE_DATA *p_struct, const char *p_src);

/** Setter.
 * Use this function to set the member "url" (see @ref OH_INSTITUTE_DATA_url)
*/
void OH_InstituteData_SetUrl(OH_INSTITUTE_DATA *p_struct, const char *p_src);

/** Setter.
 * Use this function to set the member "lastOfxValidationTime" (see @ref OH_INSTITUTE_DATA_lastOfxValidationTime)
*/
void OH_InstituteData_SetLastOfxValidationTime(OH_INSTITUTE_DATA *p_struct, const GWEN_TIME *p_src);

/** Setter.
 * Use this function to set the member "lastSslValidationTime" (see @ref OH_INSTITUTE_DATA_lastSslValidationTime)
*/
void OH_InstituteData_SetLastSslValidationTime(OH_INSTITUTE_DATA *p_struct, const GWEN_TIME *p_src);

/** Setter.
 * Use this function to set the member "fileName" (see @ref OH_INSTITUTE_DATA_fileName)
*/
void OH_InstituteData_SetFileName(OH_INSTITUTE_DATA *p_struct, const char *p_src);

OH_INSTITUTE_DATA_LIST *OH_InstituteData_List_dup(const OH_INSTITUTE_DATA_LIST *p_src);

void OH_InstituteData_ReadDb(OH_INSTITUTE_DATA *p_struct, GWEN_DB_NODE *p_db);

int OH_InstituteData_WriteDb(const OH_INSTITUTE_DATA *p_struct, GWEN_DB_NODE *p_db);

OH_INSTITUTE_DATA *OH_InstituteData_fromDb(GWEN_DB_NODE *p_db);

int OH_InstituteData_toDb(const OH_INSTITUTE_DATA *p_struct, GWEN_DB_NODE *p_db);

OH_INSTITUTE_DATA *OH_InstituteData_List_GetById(const OH_INSTITUTE_DATA_LIST *p_list, int p_cmp);



#ifdef __cplusplus
}
#endif

#endif

