/**********************************************************
 * This file has been automatically created by "typemaker2"
 * from the file "oh_institute_data.xml".
 * Please do not edit this file, all changes will be lost.
 * Better edit the mentioned source file instead.
 **********************************************************/

#ifndef OH_INSTITUTE_DATA_OH_INSTITUTE_DATA_P_H
#define OH_INSTITUTE_DATA_OH_INSTITUTE_DATA_P_H

#include "./oh_institute_data.h"


#ifdef __cplusplus
extern "C" {
#endif

struct OH_INSTITUTE_DATA {
  GWEN_LIST_ELEMENT(OH_INSTITUTE_DATA)
  int _refCount;
  int id;
  uint32_t flags;
  char *name;
  char *fid;
  char *org;
  char *brokerId;
  char *url;
  GWEN_TIME *lastOfxValidationTime;
  GWEN_TIME *lastSslValidationTime;
  char *fileName; /* volatile */
};

#ifdef __cplusplus
}
#endif

#endif

