/**********************************************************
 * This file has been automatically created by "typemaker2"
 * from the file "oh_institute_spec.xml".
 * Please do not edit this file, all changes will be lost.
 * Better edit the mentioned source file instead.
 **********************************************************/

#ifndef OH_INSTITUTE_SPEC_OH_INSTITUTE_SPEC_P_H
#define OH_INSTITUTE_SPEC_OH_INSTITUTE_SPEC_P_H

#include "./oh_institute_spec.h"


#ifdef __cplusplus
extern "C" {
#endif

struct OH_INSTITUTE_SPEC {
  GWEN_LIST_ELEMENT(OH_INSTITUTE_SPEC)
  int _refCount;
  int id;
  char *name;
};

#ifdef __cplusplus
}
#endif

#endif

