/* This file is auto-generated from "bankinfo.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef BANKINFO_P_H
#define BANKINFO_P_H

#include "bankinfo_l.h"

struct AB_BANKINFO {
  GWEN_LIST_ELEMENT(AB_BANKINFO)
  int _usage;
  int _modified;

  char *country;
  char *branchId;
  char *bankId;
  char *bankName;
  char *location;
};








#endif /* BANKINFO_P_H */
