/* This file is auto-generated from "bankinfoservice.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef BANKINFOSERVICE_P_H
#define BANKINFOSERVICE_P_H

#include "bankinfoservice_l.h"


struct AB_BANKINFO_SERVICE {
  GWEN_LIST_ELEMENT(AB_BANKINFO_SERVICE)
  int _usage;
  int _modified;

  char *type;
  char *address;
  char *suffix;
  char *pversion;
  char *mode;
  uint32_t userFlags;
  char *hversion;
  char *aux1;
  char *aux2;
  char *aux3;
  char *aux4;
};














#endif /* BANKINFOSERVICE_P_H */
