/* This file is auto-generated from "bankinfo.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef BANKINFO_H
#define BANKINFO_H

/** @page P_AB_BANKINFO_PUBLIC AB_BankInfo (public)
This page describes the properties of AB_BANKINFO
@anchor AB_BANKINFO_Country
<h3>Country</h3>
<p>
</p>
<p>
Set this property with @ref AB_BankInfo_SetCountry, 
get it with @ref AB_BankInfo_GetCountry
</p>

@anchor AB_BANKINFO_BranchId
<h3>BranchId</h3>
<p>
</p>
<p>
Set this property with @ref AB_BankInfo_SetBranchId, 
get it with @ref AB_BankInfo_GetBranchId
</p>

@anchor AB_BANKINFO_BankId
<h3>BankId</h3>
<p>
</p>
<p>
Set this property with @ref AB_BankInfo_SetBankId, 
get it with @ref AB_BankInfo_GetBankId
</p>

@anchor AB_BANKINFO_BankName
<h3>BankName</h3>
<p>
</p>
<p>
Set this property with @ref AB_BankInfo_SetBankName, 
get it with @ref AB_BankInfo_GetBankName
</p>

@anchor AB_BANKINFO_Location
<h3>Location</h3>
<p>
</p>
<p>
Set this property with @ref AB_BankInfo_SetLocation, 
get it with @ref AB_BankInfo_GetLocation
</p>

*/
#include <gwenhywfar/db.h>
#include <gwenhywfar/list2.h>
#include <gwenhywfar/types.h>
#include <aqbanking/error.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct AB_BANKINFO AB_BANKINFO;

GWEN_LIST2_FUNCTION_LIB_DEFS(AB_BANKINFO, AB_BankInfo, AQBANKING_API)

void AB_BankInfo_List2_freeAll(AB_BANKINFO_LIST2 *stl);

AB_BANKINFO *AB_BankInfo_new();
void AB_BankInfo_free(AB_BANKINFO *st);
void AB_BankInfo_Attach(AB_BANKINFO *st);
AB_BANKINFO *AB_BankInfo_dup(const AB_BANKINFO*st);
AB_BANKINFO *AB_BankInfo_fromDb(GWEN_DB_NODE *db);
int AB_BankInfo_toDb(const AB_BANKINFO*st, GWEN_DB_NODE *db);
int AB_BankInfo_IsModified(const AB_BANKINFO *st);
void AB_BankInfo_SetModified(AB_BANKINFO *st, int i);

/**
* Returns the property @ref AB_BANKINFO_Country
*/
const char *AB_BankInfo_GetCountry(const AB_BANKINFO *el);
/**
* Set the property @ref AB_BANKINFO_Country
*/
void AB_BankInfo_SetCountry(AB_BANKINFO *el, const char *d);

/**
* Returns the property @ref AB_BANKINFO_BranchId
*/
const char *AB_BankInfo_GetBranchId(const AB_BANKINFO *el);
/**
* Set the property @ref AB_BANKINFO_BranchId
*/
void AB_BankInfo_SetBranchId(AB_BANKINFO *el, const char *d);

/**
* Returns the property @ref AB_BANKINFO_BankId
*/
const char *AB_BankInfo_GetBankId(const AB_BANKINFO *el);
/**
* Set the property @ref AB_BANKINFO_BankId
*/
void AB_BankInfo_SetBankId(AB_BANKINFO *el, const char *d);

/**
* Returns the property @ref AB_BANKINFO_BankName
*/
const char *AB_BankInfo_GetBankName(const AB_BANKINFO *el);
/**
* Set the property @ref AB_BANKINFO_BankName
*/
void AB_BankInfo_SetBankName(AB_BANKINFO *el, const char *d);

/**
* Returns the property @ref AB_BANKINFO_Location
*/
const char *AB_BankInfo_GetLocation(const AB_BANKINFO *el);
/**
* Set the property @ref AB_BANKINFO_Location
*/
void AB_BankInfo_SetLocation(AB_BANKINFO *el, const char *d);


#ifdef __cplusplus
} /* __cplusplus */
#endif


#endif /* BANKINFO_H */
