/* This file is auto-generated from "bankinfo.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifdef HAVE_CONFIG_H
# include "config.h"
#endif

#include "bankinfo_p.h"
#include <gwenhywfar/misc.h>
#include <gwenhywfar/db.h>
#include <gwenhywfar/debug.h>
#include <assert.h>
#include <stdlib.h>


GWEN_LIST_FUNCTIONS(AB_BANKINFO, AB_BankInfo)
GWEN_LIST2_FUNCTIONS(AB_BANKINFO, AB_BankInfo)


AB_BANKINFO *AB_BankInfo_new() {
  AB_BANKINFO *st;

  GWEN_NEW_OBJECT(AB_BANKINFO, st)
  st->_usage=1;
  GWEN_LIST_INIT(AB_BANKINFO, st)
  st->services=AB_BankInfoService_List_new();
  return st;
}


void AB_BankInfo_free(AB_BANKINFO *st) {
  if (st) {
    assert(st->_usage);
    if (--(st->_usage)==0) {
  if (st->country)
    free(st->country);
  if (st->branchId)
    free(st->branchId);
  if (st->bankId)
    free(st->bankId);
  if (st->bankName)
    free(st->bankName);
  if (st->location)
    free(st->location);
  if (st->services)
    AB_BankInfoService_List_free(st->services);
  GWEN_LIST_FINI(AB_BANKINFO, st)
  GWEN_FREE_OBJECT(st);
    }
  }

}


AB_BANKINFO *AB_BankInfo_dup(const AB_BANKINFO *d) {
  AB_BANKINFO *st;

  assert(d);
  st=AB_BankInfo_new();
  if (d->country)
    st->country=strdup(d->country);
  if (d->branchId)
    st->branchId=strdup(d->branchId);
  if (d->bankId)
    st->bankId=strdup(d->bankId);
  if (d->bankName)
    st->bankName=strdup(d->bankName);
  if (d->location)
    st->location=strdup(d->location);
  if (d->services)
    st->services=AB_BankInfoService_List_dup(d->services);
  return st;
}


int AB_BankInfo_toDb(const AB_BANKINFO *st, GWEN_DB_NODE *db) {
  assert(st);
  assert(db);
  if (st->country)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "country", st->country))
      return -1;
  if (st->branchId)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "branchId", st->branchId))
      return -1;
  if (st->bankId)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "bankId", st->bankId))
      return -1;
  if (st->bankName)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "bankName", st->bankName))
      return -1;
  if (st->location)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "location", st->location))
      return -1;
  if (st->services)
  if (1) {
    GWEN_DB_NODE *dbT;
  
AB_BANKINFO_SERVICE *e;

    dbT=GWEN_DB_GetGroup(db, GWEN_PATH_FLAGS_CREATE_GROUP, "services");
    assert(dbT);
    e=AB_BankInfoService_List_First(st->services);
    while(e) {
      if (AB_BankInfoService_toDb(e, GWEN_DB_GetGroup(dbT, GWEN_PATH_FLAGS_CREATE_GROUP, "element")))
        return -1;
      e=AB_BankInfoService_List_Next(e);
    } /* while */
  } /* if (1) */
  return 0;
}


AB_BANKINFO *AB_BankInfo_fromDb(GWEN_DB_NODE *db) {
AB_BANKINFO *st;

  assert(db);
  st=AB_BankInfo_new();
  AB_BankInfo_SetCountry(st, GWEN_DB_GetCharValue(db, "country", 0, 0));
  AB_BankInfo_SetBranchId(st, GWEN_DB_GetCharValue(db, "branchId", 0, 0));
  AB_BankInfo_SetBankId(st, GWEN_DB_GetCharValue(db, "bankId", 0, 0));
  AB_BankInfo_SetBankName(st, GWEN_DB_GetCharValue(db, "bankName", 0, 0));
  AB_BankInfo_SetLocation(st, GWEN_DB_GetCharValue(db, "location", 0, 0));
  st->services=AB_BankInfoService_List_new();
  if (1) {
    GWEN_DB_NODE *dbT;
    AB_BANKINFO_SERVICE *e;

    dbT=GWEN_DB_GetGroup(db, GWEN_PATH_FLAGS_NAMEMUSTEXIST, "services");
    if (dbT) {
      GWEN_DB_NODE *dbT2;

      dbT2=GWEN_DB_FindFirstGroup(dbT, "element");
      while(dbT2) {
        e=AB_BankInfoService_fromDb(dbT2);
        if (!e) {
          DBG_ERROR(0, "Bad element for type \"AB_BANKINFO_SERVICE\"");
          if (GWEN_Logger_GetLevel(0)>=GWEN_LoggerLevelDebug)
            GWEN_DB_Dump(dbT2, stderr, 2);
          AB_BankInfo_free(st);
          return 0;
        }
        AB_BankInfoService_List_Add(e, st->services);    dbT2=GWEN_DB_FindNextGroup(dbT2, "element");
      } /* while */
    } /* if (dbT) */
  } /* if (1) */
  st->_modified=0;
  return st;
}


const char *AB_BankInfo_GetCountry(const AB_BANKINFO *st) {
  assert(st);
  return st->country;
}


void AB_BankInfo_SetCountry(AB_BANKINFO *st, const char *d) {
  assert(st);
  if (st->country)
    free(st->country);
  if (d)
    st->country=strdup(d);
  else
    st->country=0;
  st->_modified=1;
}


const char *AB_BankInfo_GetBranchId(const AB_BANKINFO *st) {
  assert(st);
  return st->branchId;
}


void AB_BankInfo_SetBranchId(AB_BANKINFO *st, const char *d) {
  assert(st);
  if (st->branchId)
    free(st->branchId);
  if (d)
    st->branchId=strdup(d);
  else
    st->branchId=0;
  st->_modified=1;
}


const char *AB_BankInfo_GetBankId(const AB_BANKINFO *st) {
  assert(st);
  return st->bankId;
}


void AB_BankInfo_SetBankId(AB_BANKINFO *st, const char *d) {
  assert(st);
  if (st->bankId)
    free(st->bankId);
  if (d)
    st->bankId=strdup(d);
  else
    st->bankId=0;
  st->_modified=1;
}


const char *AB_BankInfo_GetBankName(const AB_BANKINFO *st) {
  assert(st);
  return st->bankName;
}


void AB_BankInfo_SetBankName(AB_BANKINFO *st, const char *d) {
  assert(st);
  if (st->bankName)
    free(st->bankName);
  if (d)
    st->bankName=strdup(d);
  else
    st->bankName=0;
  st->_modified=1;
}


const char *AB_BankInfo_GetLocation(const AB_BANKINFO *st) {
  assert(st);
  return st->location;
}


void AB_BankInfo_SetLocation(AB_BANKINFO *st, const char *d) {
  assert(st);
  if (st->location)
    free(st->location);
  if (d)
    st->location=strdup(d);
  else
    st->location=0;
  st->_modified=1;
}


AB_BANKINFO_SERVICE_LIST *AB_BankInfo_GetServices(const AB_BANKINFO *st) {
  assert(st);
  return st->services;
}


void AB_BankInfo_SetServices(AB_BANKINFO *st, AB_BANKINFO_SERVICE_LIST *d) {
  assert(st);
  if (st->services)
    AB_BankInfoService_List_free(st->services);
  st->services=AB_BankInfoService_List_new();
  if (d) {
    AB_BANKINFO_SERVICE *e;

    e=AB_BankInfoService_List_First(d);
    while(e) {
      AB_BANKINFO_SERVICE *ne;

      ne=AB_BankInfoService_dup(e);
      assert(ne);
      AB_BankInfoService_List_Add(ne, st->services);
      e=AB_BankInfoService_List_Next(e);
    } /* while (e) */
  } /* if LIST */
  else
    st->services=0;
  st->_modified=1;
}


int AB_BankInfo_IsModified(const AB_BANKINFO *st) {
  assert(st);
  return st->_modified;
}


void AB_BankInfo_SetModified(AB_BANKINFO *st, int i) {
  assert(st);
  st->_modified=i;
}


void AB_BankInfo_Attach(AB_BANKINFO *st) {
  assert(st);
  st->_usage++;
}
AB_BANKINFO *AB_BankInfo_List2__freeAll_cb(AB_BANKINFO *st, void *user_data) {
  AB_BankInfo_free(st);
return 0;
}


void AB_BankInfo_List2_freeAll(AB_BANKINFO_LIST2 *stl) {
  if (stl) {
    AB_BankInfo_List2_ForEach(stl, AB_BankInfo_List2__freeAll_cb, 0);
    AB_BankInfo_List2_free(stl); 
  }
}


AB_BANKINFO_LIST2 *AB_BankInfo_List2_dup(const AB_BANKINFO_LIST2 *stl) {
  if (stl) {
    AB_BANKINFO_LIST2 *nl;
    AB_BANKINFO_LIST2_ITERATOR *it;

    nl=AB_BankInfo_List2_new();
    it=AB_BankInfo_List2_First(stl);
    if (it) {
      AB_BANKINFO *e;

      e=AB_BankInfo_List2Iterator_Data(it);
      assert(e);
      while(e) {
        AB_BANKINFO *ne;

        ne=AB_BankInfo_dup(e);
        assert(ne);
        AB_BankInfo_List2_PushBack(nl, ne);
        e=AB_BankInfo_List2Iterator_Next(it);
      } /* while (e) */
        AB_BankInfo_List2Iterator_free(it);
    } /* if (it) */
    return nl;
  }
  else
    return 0;
}


AB_BANKINFO_LIST *AB_BankInfo_List_dup(const AB_BANKINFO_LIST *stl) {
  if (stl) {
    AB_BANKINFO_LIST *nl;
    AB_BANKINFO *e;

    nl=AB_BankInfo_List_new();
    e=AB_BankInfo_List_First(stl);
    while(e) {
      AB_BANKINFO *ne;

      ne=AB_BankInfo_dup(e);
      assert(ne);
      AB_BankInfo_List_Add(ne, nl);
      e=AB_BankInfo_List_Next(e);
    } /* while (e) */
    return nl;
  }
  else
    return 0;
}



