/* This file is auto-generated from "bankinfo.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef BANKINFO_L_H
#define BANKINFO_L_H

/** @page P_AB_BANKINFO_LIB AB_BankInfo (lib)
This page describes the properties of AB_BANKINFO
*/
#include <gwenhywfar/misc.h>
#include "bankinfo.h"
#include <gwenhywfar/misc.h>

#ifdef __cplusplus
extern "C" {
#endif

GWEN_LIST_FUNCTION_DEFS(AB_BANKINFO, AB_BankInfo)
AB_BANKINFO_LIST *AB_BankInfo_List_dup(const AB_BANKINFO_LIST *stl);








#ifdef __cplusplus
} /* __cplusplus */
#endif


#endif /* BANKINFO_L_H */
