/* This file is auto-generated from "bankinfo.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef BANKINFO_L_H
#define BANKINFO_L_H

/** @page P_AB_BANKINFO_LIB AB_BankInfo (lib)
This page describes the properties of AB_BANKINFO
*/
#include "bankinfo.h"

#ifdef __cplusplus
extern "C" {
#endif



















#ifdef __cplusplus
} /* __cplusplus */
#endif


#endif /* BANKINFO_L_H */
