/* This file is auto-generated from "bankinfoservice.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef BANKINFOSERVICE_L_H
#define BANKINFOSERVICE_L_H

/** @page P_AB_BANKINFO_SERVICE_LIB AB_BankInfoService (lib)
This page describes the properties of AB_BANKINFO_SERVICE
*/
#include "bankinfoservice.h"

#ifdef __cplusplus
extern "C" {
#endif















#ifdef __cplusplus
} /* __cplusplus */
#endif


#endif /* BANKINFOSERVICE_L_H */
