/* This file is auto-generated from "eutransferinfo.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef EUTRANSFERINFO_L_H
#define EUTRANSFERINFO_L_H

/** @page P_AB_EUTRANSFER_INFO_LIB AB_EuTransferInfo (lib)
This page describes the properties of AB_EUTRANSFER_INFO
*/
#include "eutransferinfo.h"

#ifdef __cplusplus
extern "C" {
#endif








#ifdef __cplusplus
} /* __cplusplus */
#endif


#endif /* EUTRANSFERINFO_L_H */
