/* This file is auto-generated from "eutransferinfo.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef EUTRANSFERINFO_P_H
#define EUTRANSFERINFO_P_H

#include "eutransferinfo_l.h"


struct AB_EUTRANSFER_INFO {
  GWEN_LIST_ELEMENT(AB_EUTRANSFER_INFO)
  int _usage;
  int _modified;

  char *countryCode;
  AB_TRANSACTION_LIMITS *fieldLimits;
  AB_VALUE *limitLocalValue;
  AB_VALUE *limitForeignValue;
};







#endif /* EUTRANSFERINFO_P_H */
