/* This file is auto-generated from "message.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef MESSAGE_L_H
#define MESSAGE_L_H

/** @page P_AB_MESSAGE_LIB AB_Message (lib)
This page describes the properties of AB_MESSAGE
*/
#include "message.h"

#ifdef __cplusplus
extern "C" {
#endif









#ifdef __cplusplus
} /* __cplusplus */
#endif


#endif /* MESSAGE_L_H */
