/* This file is auto-generated from "pin.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef PIN_L_H
#define PIN_L_H

/** @page P_AB_PIN_LIB AB_Pin (lib)
This page describes the properties of AB_PIN
*/
#ifdef __cplusplus
extern "C" {
#endif

typedef struct AB_PIN AB_PIN;

#ifdef __cplusplus
} /* __cplusplus */
#endif

#include <gwenhywfar/misc.h>
#include <gwenhywfar/list2.h>
#include <gwenhywfar/misc.h>
#include <gwenhywfar/db.h>
#include <gwenhywfar/types.h>
#include <aqbanking/banking.h>

#ifdef __cplusplus
extern "C" {
#endif


GWEN_LIST_FUNCTION_DEFS(AB_PIN, AB_Pin)
AB_PIN_LIST *AB_Pin_List_dup(const AB_PIN_LIST *stl);

GWEN_LIST2_FUNCTION_DEFS(AB_PIN, AB_Pin)

void AB_Pin_List2_freeAll(AB_PIN_LIST2 *stl);

AB_PIN *AB_Pin_new(void);
AB_PIN *AB_Pin_fromDb(GWEN_DB_NODE *db);
AB_PIN *AB_Pin_dup(const AB_PIN*st);
void AB_Pin_free(AB_PIN *st);
void AB_Pin_Attach(AB_PIN *st);
int AB_Pin_ReadDb(AB_PIN *st, GWEN_DB_NODE *db);
int AB_Pin_toDb(const AB_PIN*st, GWEN_DB_NODE *db);
int AB_Pin_IsModified(const AB_PIN *st);
void AB_Pin_SetModified(AB_PIN *st, int i);

/**
* Returns the property @ref AB_PIN_Token
*/
AQBANKING_API const char *AB_Pin_GetToken(const AB_PIN *el);
/**
* Set the property @ref AB_PIN_Token
*/
AQBANKING_API void AB_Pin_SetToken(AB_PIN *el, const char *d);

/**
* Returns the property @ref AB_PIN_Value
*/
AQBANKING_API const char *AB_Pin_GetValue(const AB_PIN *el);
/**
* Set the property @ref AB_PIN_Value
*/
AQBANKING_API void AB_Pin_SetValue(AB_PIN *el, const char *d);

/**
* Returns the property @ref AB_PIN_Hash
*/
AQBANKING_API const char *AB_Pin_GetHash(const AB_PIN *el);
/**
* Set the property @ref AB_PIN_Hash
*/
AQBANKING_API void AB_Pin_SetHash(AB_PIN *el, const char *d);

/**
* Returns the property @ref AB_PIN_Status
*/
AQBANKING_API const char *AB_Pin_GetStatus(const AB_PIN *el);
/**
* Set the property @ref AB_PIN_Status
*/
AQBANKING_API void AB_Pin_SetStatus(AB_PIN *el, const char *d);


#ifdef __cplusplus
} /* __cplusplus */
#endif


#endif /* PIN_L_H */
