/* This file is auto-generated from "security.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef SECURITY_P_H
#define SECURITY_P_H

#include "security_l.h"


struct AB_SECURITY {
  GWEN_LIST_ELEMENT(AB_SECURITY)
  int _usage;
  int _modified;

  char *name;
  char *uniqueId;
  char *nameSpace;
  char *tickerSymbol;
  AB_VALUE *units;
  AB_VALUE *unitPriceValue;
  GWEN_TIME *unitPriceDate;
};










#endif /* SECURITY_P_H */
