/* This file is auto-generated from "security.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef SECURITY_L_H
#define SECURITY_L_H

/** @page P_AB_SECURITY_LIB AB_Security (lib)
This page describes the properties of AB_SECURITY
*/
#include "security.h"

#ifdef __cplusplus
extern "C" {
#endif











#ifdef __cplusplus
} /* __cplusplus */
#endif


#endif /* SECURITY_L_H */
