/* This file is auto-generated from "split.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef SPLIT_P_H
#define SPLIT_P_H

#include "split_l.h"

struct AB_SPLIT {
  GWEN_INHERIT_ELEMENT(AB_SPLIT)
  GWEN_LIST_ELEMENT(AB_SPLIT)
  int _usage;
  int _modified;

  char *localCountry;
  char *localBankCode;
  char *localBranchId;
  char *localAccountNumber;
  char *localSuffix;
  char *localName;
  char *remoteCountry;
  char *remoteBankCode;
  char *remoteBranchId;
  char *remoteAccountNumber;
  char *remoteSuffix;
  GWEN_STRINGLIST *remoteName;
  AB_VALUE *value;
  GWEN_STRINGLIST *purpose;
};



/** @name Local Account Info
 *
This group contains information about the local account.
*/
/*@{*/







/*@}*/

/** @name Remote Account Info
 *
This group contains information about the remote account.
*/
/*@{*/







/*@}*/

/** @name Value
*/
/*@{*/

/*@}*/



#endif /* SPLIT_P_H */
