/* This file is auto-generated from "split.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifdef HAVE_CONFIG_H
# include "config.h"
#endif

#include "split_p.h"
#include <gwenhywfar/misc.h>
#include <gwenhywfar/db.h>
#include <gwenhywfar/debug.h>
#include <assert.h>
#include <stdlib.h>


GWEN_INHERIT_FUNCTIONS(AB_SPLIT)
GWEN_LIST_FUNCTIONS(AB_SPLIT, AB_Split)
GWEN_LIST2_FUNCTIONS(AB_SPLIT, AB_Split)


AB_SPLIT *AB_Split_new() {
  AB_SPLIT *st;

  GWEN_NEW_OBJECT(AB_SPLIT, st)
  st->_usage=1;
  GWEN_INHERIT_INIT(AB_SPLIT, st)
  GWEN_LIST_INIT(AB_SPLIT, st)
  st->remoteName=GWEN_StringList_new();
  st->purpose=GWEN_StringList_new();
  return st;
}


void AB_Split_free(AB_SPLIT *st) {
  if (st) {
    assert(st->_usage);
    if (--(st->_usage)==0) {
  GWEN_INHERIT_FINI(AB_SPLIT, st)
  if (st->localCountry)
    free(st->localCountry);
  if (st->localBankCode)
    free(st->localBankCode);
  if (st->localBranchId)
    free(st->localBranchId);
  if (st->localAccountNumber)
    free(st->localAccountNumber);
  if (st->localSuffix)
    free(st->localSuffix);
  if (st->localName)
    free(st->localName);
  if (st->remoteCountry)
    free(st->remoteCountry);
  if (st->remoteBankCode)
    free(st->remoteBankCode);
  if (st->remoteBranchId)
    free(st->remoteBranchId);
  if (st->remoteAccountNumber)
    free(st->remoteAccountNumber);
  if (st->remoteSuffix)
    free(st->remoteSuffix);
  if (st->remoteName)
    GWEN_StringList_free(st->remoteName);
  if (st->value)
    AB_Value_free(st->value);
  if (st->purpose)
    GWEN_StringList_free(st->purpose);
  GWEN_LIST_FINI(AB_SPLIT, st)
  GWEN_FREE_OBJECT(st);
    }
  }

}


AB_SPLIT *AB_Split_dup(const AB_SPLIT *d) {
  AB_SPLIT *st;

  assert(d);
  st=AB_Split_new();
  if (d->localCountry)
    st->localCountry=strdup(d->localCountry);
  if (d->localBankCode)
    st->localBankCode=strdup(d->localBankCode);
  if (d->localBranchId)
    st->localBranchId=strdup(d->localBranchId);
  if (d->localAccountNumber)
    st->localAccountNumber=strdup(d->localAccountNumber);
  if (d->localSuffix)
    st->localSuffix=strdup(d->localSuffix);
  if (d->localName)
    st->localName=strdup(d->localName);
  if (d->remoteCountry)
    st->remoteCountry=strdup(d->remoteCountry);
  if (d->remoteBankCode)
    st->remoteBankCode=strdup(d->remoteBankCode);
  if (d->remoteBranchId)
    st->remoteBranchId=strdup(d->remoteBranchId);
  if (d->remoteAccountNumber)
    st->remoteAccountNumber=strdup(d->remoteAccountNumber);
  if (d->remoteSuffix)
    st->remoteSuffix=strdup(d->remoteSuffix);
  if (d->remoteName)
    st->remoteName=GWEN_StringList_dup(d->remoteName);
  if (d->value)
    st->value=AB_Value_dup(d->value);
  if (d->purpose)
    st->purpose=GWEN_StringList_dup(d->purpose);
  return st;
}


int AB_Split_toDb(const AB_SPLIT *st, GWEN_DB_NODE *db) {
  assert(st);
  assert(db);
  if (st->localCountry)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "localCountry", st->localCountry))
      return -1;
  if (st->localBankCode)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "localBankCode", st->localBankCode))
      return -1;
  if (st->localBranchId)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "localBranchId", st->localBranchId))
      return -1;
  if (st->localAccountNumber)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "localAccountNumber", st->localAccountNumber))
      return -1;
  if (st->localSuffix)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "localSuffix", st->localSuffix))
      return -1;
  if (st->localName)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "localName", st->localName))
      return -1;
  if (st->remoteCountry)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "remoteCountry", st->remoteCountry))
      return -1;
  if (st->remoteBankCode)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "remoteBankCode", st->remoteBankCode))
      return -1;
  if (st->remoteBranchId)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "remoteBranchId", st->remoteBranchId))
      return -1;
  if (st->remoteAccountNumber)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "remoteAccountNumber", st->remoteAccountNumber))
      return -1;
  if (st->remoteSuffix)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "remoteSuffix", st->remoteSuffix))
      return -1;
  if (st->remoteName)
    {
      GWEN_STRINGLISTENTRY *se;

      GWEN_DB_DeleteVar(db, "remoteName");
      se=GWEN_StringList_FirstEntry(st->remoteName);
      while(se) {
        const char *s;

        s=GWEN_StringListEntry_Data(se);
        assert(s);
        if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_DEFAULT, "remoteName", s))
          return -1;
        se=GWEN_StringListEntry_Next(se);
      } /* while */
    }
  if (st->value)
    if (AB_Value_toDb(st->value, GWEN_DB_GetGroup(db, GWEN_DB_FLAGS_DEFAULT, "value")))
      return -1;
  if (st->purpose)
    {
      GWEN_STRINGLISTENTRY *se;

      GWEN_DB_DeleteVar(db, "purpose");
      se=GWEN_StringList_FirstEntry(st->purpose);
      while(se) {
        const char *s;

        s=GWEN_StringListEntry_Data(se);
        assert(s);
        if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_DEFAULT, "purpose", s))
          return -1;
        se=GWEN_StringListEntry_Next(se);
      } /* while */
    }
  return 0;
}


AB_SPLIT *AB_Split_fromDb(GWEN_DB_NODE *db) {
AB_SPLIT *st;

  assert(db);
  st=AB_Split_new();
  AB_Split_SetLocalCountry(st, GWEN_DB_GetCharValue(db, "localCountry", 0, 0));
  AB_Split_SetLocalBankCode(st, GWEN_DB_GetCharValue(db, "localBankCode", 0, 0));
  AB_Split_SetLocalBranchId(st, GWEN_DB_GetCharValue(db, "localBranchId", 0, 0));
  AB_Split_SetLocalAccountNumber(st, GWEN_DB_GetCharValue(db, "localAccountNumber", 0, 0));
  AB_Split_SetLocalSuffix(st, GWEN_DB_GetCharValue(db, "localSuffix", 0, 0));
  AB_Split_SetLocalName(st, GWEN_DB_GetCharValue(db, "localName", 0, 0));
  AB_Split_SetRemoteCountry(st, GWEN_DB_GetCharValue(db, "remoteCountry", 0, 0));
  AB_Split_SetRemoteBankCode(st, GWEN_DB_GetCharValue(db, "remoteBankCode", 0, 0));
  AB_Split_SetRemoteBranchId(st, GWEN_DB_GetCharValue(db, "remoteBranchId", 0, 0));
  AB_Split_SetRemoteAccountNumber(st, GWEN_DB_GetCharValue(db, "remoteAccountNumber", 0, 0));
  AB_Split_SetRemoteSuffix(st, GWEN_DB_GetCharValue(db, "remoteSuffix", 0, 0));
  if (1) {
    int i;

    for (i=0; ; i++) {
      const char *s;

      s=GWEN_DB_GetCharValue(db, "remoteName", i, 0);
      if (!s)
        break;
      AB_Split_AddRemoteName(st, s, 0);
    } /* for */
  }
  if (1) {
    GWEN_DB_NODE *dbT;

    dbT=GWEN_DB_GetGroup(db, GWEN_PATH_FLAGS_NAMEMUSTEXIST, "value");
    if (dbT)  AB_Split_SetValue(st, AB_Value_fromDb(dbT));
  }
  if (1) {
    int i;

    for (i=0; ; i++) {
      const char *s;

      s=GWEN_DB_GetCharValue(db, "purpose", i, 0);
      if (!s)
        break;
      AB_Split_AddPurpose(st, s, 0);
    } /* for */
  }
  st->_modified=0;
  return st;
}


const char *AB_Split_GetLocalCountry(const AB_SPLIT *st) {
  assert(st);
  return st->localCountry;
}


void AB_Split_SetLocalCountry(AB_SPLIT *st, const char *d) {
  assert(st);
  if (st->localCountry)
    free(st->localCountry);
  if (d)
    st->localCountry=strdup(d);
  else
    st->localCountry=0;
  st->_modified=1;
}


const char *AB_Split_GetLocalBankCode(const AB_SPLIT *st) {
  assert(st);
  return st->localBankCode;
}


void AB_Split_SetLocalBankCode(AB_SPLIT *st, const char *d) {
  assert(st);
  if (st->localBankCode)
    free(st->localBankCode);
  if (d)
    st->localBankCode=strdup(d);
  else
    st->localBankCode=0;
  st->_modified=1;
}


const char *AB_Split_GetLocalBranchId(const AB_SPLIT *st) {
  assert(st);
  return st->localBranchId;
}


void AB_Split_SetLocalBranchId(AB_SPLIT *st, const char *d) {
  assert(st);
  if (st->localBranchId)
    free(st->localBranchId);
  if (d)
    st->localBranchId=strdup(d);
  else
    st->localBranchId=0;
  st->_modified=1;
}


const char *AB_Split_GetLocalAccountNumber(const AB_SPLIT *st) {
  assert(st);
  return st->localAccountNumber;
}


void AB_Split_SetLocalAccountNumber(AB_SPLIT *st, const char *d) {
  assert(st);
  if (st->localAccountNumber)
    free(st->localAccountNumber);
  if (d)
    st->localAccountNumber=strdup(d);
  else
    st->localAccountNumber=0;
  st->_modified=1;
}


const char *AB_Split_GetLocalSuffix(const AB_SPLIT *st) {
  assert(st);
  return st->localSuffix;
}


void AB_Split_SetLocalSuffix(AB_SPLIT *st, const char *d) {
  assert(st);
  if (st->localSuffix)
    free(st->localSuffix);
  if (d)
    st->localSuffix=strdup(d);
  else
    st->localSuffix=0;
  st->_modified=1;
}


const char *AB_Split_GetLocalName(const AB_SPLIT *st) {
  assert(st);
  return st->localName;
}


void AB_Split_SetLocalName(AB_SPLIT *st, const char *d) {
  assert(st);
  if (st->localName)
    free(st->localName);
  if (d)
    st->localName=strdup(d);
  else
    st->localName=0;
  st->_modified=1;
}


const char *AB_Split_GetRemoteCountry(const AB_SPLIT *st) {
  assert(st);
  return st->remoteCountry;
}


void AB_Split_SetRemoteCountry(AB_SPLIT *st, const char *d) {
  assert(st);
  if (st->remoteCountry)
    free(st->remoteCountry);
  if (d)
    st->remoteCountry=strdup(d);
  else
    st->remoteCountry=0;
  st->_modified=1;
}


const char *AB_Split_GetRemoteBankCode(const AB_SPLIT *st) {
  assert(st);
  return st->remoteBankCode;
}


void AB_Split_SetRemoteBankCode(AB_SPLIT *st, const char *d) {
  assert(st);
  if (st->remoteBankCode)
    free(st->remoteBankCode);
  if (d)
    st->remoteBankCode=strdup(d);
  else
    st->remoteBankCode=0;
  st->_modified=1;
}


const char *AB_Split_GetRemoteBranchId(const AB_SPLIT *st) {
  assert(st);
  return st->remoteBranchId;
}


void AB_Split_SetRemoteBranchId(AB_SPLIT *st, const char *d) {
  assert(st);
  if (st->remoteBranchId)
    free(st->remoteBranchId);
  if (d)
    st->remoteBranchId=strdup(d);
  else
    st->remoteBranchId=0;
  st->_modified=1;
}


const char *AB_Split_GetRemoteAccountNumber(const AB_SPLIT *st) {
  assert(st);
  return st->remoteAccountNumber;
}


void AB_Split_SetRemoteAccountNumber(AB_SPLIT *st, const char *d) {
  assert(st);
  if (st->remoteAccountNumber)
    free(st->remoteAccountNumber);
  if (d)
    st->remoteAccountNumber=strdup(d);
  else
    st->remoteAccountNumber=0;
  st->_modified=1;
}


const char *AB_Split_GetRemoteSuffix(const AB_SPLIT *st) {
  assert(st);
  return st->remoteSuffix;
}


void AB_Split_SetRemoteSuffix(AB_SPLIT *st, const char *d) {
  assert(st);
  if (st->remoteSuffix)
    free(st->remoteSuffix);
  if (d)
    st->remoteSuffix=strdup(d);
  else
    st->remoteSuffix=0;
  st->_modified=1;
}


const GWEN_STRINGLIST *AB_Split_GetRemoteName(const AB_SPLIT *st) {
  assert(st);
  return st->remoteName;
}


void AB_Split_SetRemoteName(AB_SPLIT *st, const GWEN_STRINGLIST *d) {
  assert(st);
  if (st->remoteName)
    GWEN_StringList_free(st->remoteName);
  if (d)
    st->remoteName=GWEN_StringList_dup(d);
  else
    st->remoteName=0;
  st->_modified=1;
}


void AB_Split_AddRemoteName(AB_SPLIT *st, const char *d, int chk){
  assert(st);
  assert(d);
  if (GWEN_StringList_AppendString(st->remoteName, d, 0, chk))
    st->_modified=1;
}


void AB_Split_RemoveRemoteName(AB_SPLIT *st, const char *d) {
  if (GWEN_StringList_RemoveString(st->remoteName, d))
    st->_modified=1;
}


void AB_Split_ClearRemoteName(AB_SPLIT *st) {
  if (GWEN_StringList_Count(st->remoteName)) {
    GWEN_StringList_Clear(st->remoteName);
    st->_modified=1;
  }
}


int AB_Split_HasRemoteName(AB_SPLIT *st, const char *d) {
  return GWEN_StringList_HasString(st->remoteName, d);
}


const AB_VALUE *AB_Split_GetValue(const AB_SPLIT *st) {
  assert(st);
  return st->value;
}


void AB_Split_SetValue(AB_SPLIT *st, const AB_VALUE *d) {
  assert(st);
  if (st->value)
    AB_Value_free(st->value);
  if (d)
    st->value=AB_Value_dup(d);
  else
    st->value=0;
  st->_modified=1;
}


const GWEN_STRINGLIST *AB_Split_GetPurpose(const AB_SPLIT *st) {
  assert(st);
  return st->purpose;
}


void AB_Split_SetPurpose(AB_SPLIT *st, const GWEN_STRINGLIST *d) {
  assert(st);
  if (st->purpose)
    GWEN_StringList_free(st->purpose);
  if (d)
    st->purpose=GWEN_StringList_dup(d);
  else
    st->purpose=0;
  st->_modified=1;
}


void AB_Split_AddPurpose(AB_SPLIT *st, const char *d, int chk){
  assert(st);
  assert(d);
  if (GWEN_StringList_AppendString(st->purpose, d, 0, chk))
    st->_modified=1;
}


void AB_Split_RemovePurpose(AB_SPLIT *st, const char *d) {
  if (GWEN_StringList_RemoveString(st->purpose, d))
    st->_modified=1;
}


void AB_Split_ClearPurpose(AB_SPLIT *st) {
  if (GWEN_StringList_Count(st->purpose)) {
    GWEN_StringList_Clear(st->purpose);
    st->_modified=1;
  }
}


int AB_Split_HasPurpose(AB_SPLIT *st, const char *d) {
  return GWEN_StringList_HasString(st->purpose, d);
}


int AB_Split_IsModified(const AB_SPLIT *st) {
  assert(st);
  return st->_modified;
}


void AB_Split_SetModified(AB_SPLIT *st, int i) {
  assert(st);
  st->_modified=i;
}


void AB_Split_Attach(AB_SPLIT *st) {
  assert(st);
  st->_usage++;
}
AB_SPLIT *AB_Split_List2__freeAll_cb(AB_SPLIT *st, void *user_data) {
  AB_Split_free(st);
return 0;
}


void AB_Split_List2_freeAll(AB_SPLIT_LIST2 *stl) {
  if (stl) {
    AB_Split_List2_ForEach(stl, AB_Split_List2__freeAll_cb, 0);
    AB_Split_List2_free(stl); 
  }
}




AB_SPLIT_LIST *AB_Split_List_dup(const AB_SPLIT_LIST *stl) {
  if (stl) {
    AB_SPLIT_LIST *nl;
    AB_SPLIT *e;

    nl=AB_Split_List_new();
    e=AB_Split_List_First(stl);
    while(e) {
      AB_SPLIT *ne;

      ne=AB_Split_dup(e);
      assert(ne);
      AB_Split_List_Add(ne, nl);
      e=AB_Split_List_Next(e);
    } /* while (e) */
    return nl;
  }
  else
    return 0;
}



