/* This file is auto-generated from "split.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef SPLIT_L_H
#define SPLIT_L_H

/** @page P_AB_SPLIT_LIB AB_Split (lib)
This page describes the properties of AB_SPLIT
This type contains all important information about transaction splits. Please note that all text fields are in UTF-8.<h3>Account Info</h3>
<p>
This group contains information about the remote account.</p>
<h3>Value</h3>
<p>
</p>
*/
#include "split.h"

#ifdef __cplusplus
extern "C" {
#endif




/** @name Account Info
 *
This group contains information about the remote account.*/
/*@{*/







/*@}*/

/** @name Value
*/
/*@{*/

/*@}*/



#ifdef __cplusplus
} /* __cplusplus */
#endif


#endif /* SPLIT_L_H */
