/* This file is auto-generated from "textkeydescr.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef TEXTKEYDESCR_P_H
#define TEXTKEYDESCR_P_H

#include "textkeydescr_l.h"


struct AB_TEXTKEY_DESCR {
  GWEN_LIST_ELEMENT(AB_TEXTKEY_DESCR)
  int _usage;
  int _modified;

  int value;
  char *name;
  char *descr;
};







#endif /* TEXTKEYDESCR_P_H */
