/* This file is auto-generated from "textkeydescr.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef TEXTKEYDESCR_L_H
#define TEXTKEYDESCR_L_H

/** @page P_AB_TEXTKEY_DESCR_LIB AB_TextKeyDescr (lib)
This page describes the properties of AB_TEXTKEY_DESCR
This type contains the description of a textkey. Please note that all text fields are in UTF-8.*/
#include "textkeydescr.h"

#ifdef __cplusplus
extern "C" {
#endif








#ifdef __cplusplus
} /* __cplusplus */
#endif


#endif /* TEXTKEYDESCR_L_H */
