/* This file is auto-generated from "transaction.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef TRANSACTION_L_H
#define TRANSACTION_L_H

/** @page P_AB_TRANSACTION_LIB AB_Transaction (lib)
This page describes the properties of AB_TRANSACTION
<h3>Local Account Info</h3>
<p>
</p>
<h3>Remote Account Info</h3>
<p>
</p>
<h3>Dates</h3>
<p>
</p>
<h3>Value</h3>
<p>
</p>
<h3>Info Which Is Not Supported by All Backends</h3>
<p>
</p>
*/
#include <gwenhywfar/misc.h>
#include "transaction.h"
#include <gwenhywfar/misc.h>

#ifdef __cplusplus
extern "C" {
#endif

GWEN_LIST_FUNCTION_DEFS(AB_TRANSACTION, AB_Transaction)
AB_TRANSACTION_LIST *AB_Transaction_List_dup(const AB_TRANSACTION_LIST *stl);

/** @name Local Account Info
*/
/*@{*/






/*@}*/

/** @name Remote Account Info
*/
/*@{*/






/*@}*/


/** @name Dates
*/
/*@{*/


/*@}*/

/** @name Value
*/
/*@{*/

/*@}*/

/** @name Info Which Is Not Supported by All Backends
*/
/*@{*/









/*@}*/


#ifdef __cplusplus
} /* __cplusplus */
#endif


#endif /* TRANSACTION_L_H */
