/* This file is auto-generated from "transaction.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef TRANSACTION_L_H
#define TRANSACTION_L_H

/** @page P_AB_TRANSACTION_LIB AB_Transaction (lib)
This page describes the properties of AB_TRANSACTION
This type contains all important information about transactions. Please note that all text fields are in UTF-8.
<h3>Local Account Info</h3>
<p>
This group contains information about the local account.
</p>
<h3>Remote Account Info</h3>
<p>
This group contains information about the remote account.
</p>
<h3>Dates</h3>
<p>
</p>
<h3>Value</h3>
<p>
</p>
<h3>Info Which Is Not Supported by All Backends</h3>
<p>
<p>
This group contains information which differ between backends.
</p>
<p>
Some of this information might not even be
<b>
supported
</b>
by every backends.
</p>
</p>
*/
#include <gwenhywfar/misc.h>
#include "transaction.h"
#include <gwenhywfar/misc.h>

#ifdef __cplusplus
extern "C" {
#endif

GWEN_LIST_FUNCTION_DEFS(AB_TRANSACTION, AB_Transaction)


/** @name Local Account Info
 *
This group contains information about the local account.
*/
/*@{*/







/*@}*/

/** @name Remote Account Info
 *
This group contains information about the remote account.
*/
/*@{*/







/*@}*/


/** @name Dates
*/
/*@{*/


/*@}*/

/** @name Value
*/
/*@{*/

/*@}*/

/** @name Info Which Is Not Supported by All Backends
 *
<p>
This group contains information which differ between backends.
</p>
<p>
Some of this information might not even be
<b>
supported
</b>
by every backends.
</p>
*/
/*@{*/










/*@}*/


#ifdef __cplusplus
} /* __cplusplus */
#endif


#endif /* TRANSACTION_L_H */
