/* This file is auto-generated from "user.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef USER_L_H
#define USER_L_H

/** @page P_AB_USER_LIB AB_User (lib)
This page describes the properties of AB_USER
This group represents a user within AqBanking.*/
#include <gwenhywfar/misc.h>
#include "user.h"
#include <gwenhywfar/misc.h>

#ifdef __cplusplus
extern "C" {
#endif


GWEN_LIST_FUNCTION_DEFS(AB_USER, AB_User)















#ifdef __cplusplus
} /* __cplusplus */
#endif


#endif /* USER_L_H */
