/* This file is auto-generated from "user.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef USER_P_H
#define USER_P_H

#include "user_l.h"


struct AB_USER {
  GWEN_INHERIT_ELEMENT(AB_USER)
  GWEN_LIST_ELEMENT(AB_USER)
  int _usage;
  int _modified;

  uint32_t uniqueId;
  char *backendName;
  char *userName;
  char *userId;
  char *customerId;
  char *country;
  char *bankCode;
  uint32_t lastSessionId;
  GWEN_FSLOCK *fileLock;
  GWEN_DB_NODE *data;
  AB_BANKING *banking;
  char *dbId;
};

AB_USER *AB_User__new();













/**
* Returns the property @ref AB_USER_Data
*/
AQBANKING_API GWEN_DB_NODE *AB_User_GetData(const AB_USER *el);
/**
* Set the property @ref AB_USER_Data
*/
AQBANKING_API void AB_User_SetData(AB_USER *el, GWEN_DB_NODE *d);




#endif /* USER_P_H */
